/*!
 * Meridian city data.
 *
 * Every IANA time zone your browser knows about is searchable automatically
 * (via Intl.supportedValuesOf). This file adds the friendly layer on top:
 * real city names, countries and nicknames, so "Mumbai", "SF", "UAE" or "IST"
 * all find what you expect.
 *
 * Add your own cities to `cities` using the format:
 *   "City|IANA/Zone|Country|extra search words"
 */
window.MERIDIAN_ZONES = {
  // Shown when the search box is empty.
  popular: [
    'New York', 'London', 'Tokyo', 'Dubai', 'Singapore', 'Sydney',
    'Los Angeles', 'Paris', 'Mumbai', 'Berlin', 'Hong Kong', 'São Paulo'
  ],

  // Search words that apply to every city in a country.
  aliases: {
    'United States': 'US USA America',
    'United Kingdom': 'UK GB Britain',
    'United Arab Emirates': 'UAE Emirates',
    'South Korea': 'Korea',
    'Czechia': 'Czech Republic',
    'Türkiye': 'Turkey',
    'Netherlands': 'Holland',
    'DR Congo': 'Congo DRC'
  },

  // Nicer names for zone IDs that browsers report under older spellings.
  names: {
    'Asia/Calcutta': 'Kolkata',
    'Asia/Saigon': 'Ho Chi Minh City',
    'Asia/Katmandu': 'Kathmandu',
    'Asia/Rangoon': 'Yangon',
    'Europe/Kiev': 'Kyiv',
    'America/Argentina/Buenos_Aires': 'Buenos Aires',
    'America/Indiana/Indianapolis': 'Indianapolis',
    'America/Kentucky/Louisville': 'Louisville',
    'America/North_Dakota/Center': 'Center, North Dakota',
    'America/Port-au-Prince': 'Port-au-Prince',
    'Atlantic/Faeroe': 'Faroe Islands',
    'Atlantic/Reykjavik': 'Reykjavík',
    'Pacific/Truk': 'Chuuk',
    'Pacific/Ponape': 'Pohnpei',
    'Africa/Asmera': 'Asmara',
    'UTC': 'UTC'
  },

  cities: [
    // United States
    'New York|America/New_York|United States|NYC EST EDT Eastern',
    'Boston|America/New_York|United States|Massachusetts',
    'Washington DC|America/New_York|United States|Capital',
    'Miami|America/New_York|United States|Florida',
    'Atlanta|America/New_York|United States|Georgia',
    'Chicago|America/Chicago|United States|CST CDT Central Illinois',
    'Houston|America/Chicago|United States|Texas',
    'Dallas|America/Chicago|United States|Texas',
    'Austin|America/Chicago|United States|Texas',
    'Denver|America/Denver|United States|MST MDT Mountain Colorado',
    'Phoenix|America/Phoenix|United States|Arizona',
    'Los Angeles|America/Los_Angeles|United States|LA PST PDT Pacific California',
    'San Francisco|America/Los_Angeles|United States|SF Bay Area Silicon Valley California',
    'San Diego|America/Los_Angeles|United States|California',
    'Seattle|America/Los_Angeles|United States|Washington',
    'Portland|America/Los_Angeles|United States|Oregon',
    'Las Vegas|America/Los_Angeles|United States|Nevada',
    'Anchorage|America/Anchorage|United States|Alaska AKST',
    'Honolulu|Pacific/Honolulu|United States|Hawaii HST',

    // Canada
    'Toronto|America/Toronto|Canada|Ontario',
    'Ottawa|America/Toronto|Canada|Ontario',
    'Montreal|America/Toronto|Canada|Quebec',
    'Vancouver|America/Vancouver|Canada|British Columbia',
    'Calgary|America/Edmonton|Canada|Alberta',
    'Winnipeg|America/Winnipeg|Canada|Manitoba',
    'Halifax|America/Halifax|Canada|Nova Scotia',
    "St. John's|America/St_Johns|Canada|Newfoundland",

    // Latin America & Caribbean
    'Mexico City|America/Mexico_City|Mexico|CDMX',
    'Cancún|America/Cancun|Mexico|Quintana Roo',
    'Tijuana|America/Tijuana|Mexico|Baja California',
    'Guatemala City|America/Guatemala|Guatemala|',
    'San José|America/Costa_Rica|Costa Rica|',
    'Panama City|America/Panama|Panama|',
    'Havana|America/Havana|Cuba|',
    'Kingston|America/Jamaica|Jamaica|',
    'Santo Domingo|America/Santo_Domingo|Dominican Republic|',
    'San Juan|America/Puerto_Rico|Puerto Rico|',
    'Bogotá|America/Bogota|Colombia|Medellín',
    'Quito|America/Guayaquil|Ecuador|',
    'Lima|America/Lima|Peru|',
    'La Paz|America/La_Paz|Bolivia|',
    'Caracas|America/Caracas|Venezuela|',
    'Santiago|America/Santiago|Chile|',
    'Buenos Aires|America/Argentina/Buenos_Aires|Argentina|',
    'Montevideo|America/Montevideo|Uruguay|',
    'Asunción|America/Asuncion|Paraguay|',
    'São Paulo|America/Sao_Paulo|Brazil|Brasília BRT',
    'Rio de Janeiro|America/Sao_Paulo|Brazil|',

    // Europe
    'London|Europe/London|United Kingdom|GMT BST England',
    'Manchester|Europe/London|United Kingdom|England',
    'Edinburgh|Europe/London|United Kingdom|Scotland',
    'Dublin|Europe/Dublin|Ireland|',
    'Lisbon|Europe/Lisbon|Portugal|',
    'Azores|Atlantic/Azores|Portugal|Ponta Delgada',
    'Madrid|Europe/Madrid|Spain|CET CEST',
    'Barcelona|Europe/Madrid|Spain|',
    'Paris|Europe/Paris|France|CET CEST',
    'Brussels|Europe/Brussels|Belgium|',
    'Amsterdam|Europe/Amsterdam|Netherlands|',
    'Berlin|Europe/Berlin|Germany|CET CEST',
    'Munich|Europe/Berlin|Germany|',
    'Frankfurt|Europe/Berlin|Germany|',
    'Zurich|Europe/Zurich|Switzerland|',
    'Geneva|Europe/Zurich|Switzerland|',
    'Vienna|Europe/Vienna|Austria|',
    'Rome|Europe/Rome|Italy|',
    'Milan|Europe/Rome|Italy|',
    'Prague|Europe/Prague|Czechia|',
    'Warsaw|Europe/Warsaw|Poland|',
    'Budapest|Europe/Budapest|Hungary|',
    'Copenhagen|Europe/Copenhagen|Denmark|',
    'Stockholm|Europe/Stockholm|Sweden|',
    'Oslo|Europe/Oslo|Norway|',
    'Helsinki|Europe/Helsinki|Finland|EET',
    'Reykjavík|Atlantic/Reykjavik|Iceland|',
    'Athens|Europe/Athens|Greece|',
    'Bucharest|Europe/Bucharest|Romania|',
    'Sofia|Europe/Sofia|Bulgaria|',
    'Belgrade|Europe/Belgrade|Serbia|',
    'Zagreb|Europe/Zagreb|Croatia|',
    'Kyiv|Europe/Kiev|Ukraine|Kiev',
    'Istanbul|Europe/Istanbul|Türkiye|TRT',
    'Moscow|Europe/Moscow|Russia|MSK',
    'Saint Petersburg|Europe/Moscow|Russia|',
    'Novosibirsk|Asia/Novosibirsk|Russia|Siberia',
    'Vladivostok|Asia/Vladivostok|Russia|',
    'Minsk|Europe/Minsk|Belarus|',
    'Riga|Europe/Riga|Latvia|',
    'Vilnius|Europe/Vilnius|Lithuania|',
    'Tallinn|Europe/Tallinn|Estonia|',

    // Africa
    'Cairo|Africa/Cairo|Egypt|EET',
    'Lagos|Africa/Lagos|Nigeria|WAT Abuja',
    'Accra|Africa/Accra|Ghana|',
    'Dakar|Africa/Dakar|Senegal|',
    'Casablanca|Africa/Casablanca|Morocco|',
    'Algiers|Africa/Algiers|Algeria|',
    'Tunis|Africa/Tunis|Tunisia|',
    'Nairobi|Africa/Nairobi|Kenya|EAT',
    'Addis Ababa|Africa/Addis_Ababa|Ethiopia|',
    'Kampala|Africa/Kampala|Uganda|',
    'Dar es Salaam|Africa/Dar_es_Salaam|Tanzania|',
    'Kinshasa|Africa/Kinshasa|DR Congo|',
    'Luanda|Africa/Luanda|Angola|',
    'Harare|Africa/Harare|Zimbabwe|',
    'Johannesburg|Africa/Johannesburg|South Africa|SAST',
    'Cape Town|Africa/Johannesburg|South Africa|',
    'Port Louis|Indian/Mauritius|Mauritius|',
    'Antananarivo|Indian/Antananarivo|Madagascar|',

    // Middle East & Caucasus
    'Dubai|Asia/Dubai|United Arab Emirates|GST',
    'Abu Dhabi|Asia/Dubai|United Arab Emirates|',
    'Riyadh|Asia/Riyadh|Saudi Arabia|KSA AST',
    'Doha|Asia/Qatar|Qatar|',
    'Kuwait City|Asia/Kuwait|Kuwait|',
    'Manama|Asia/Bahrain|Bahrain|',
    'Muscat|Asia/Muscat|Oman|',
    'Tehran|Asia/Tehran|Iran|',
    'Baghdad|Asia/Baghdad|Iraq|',
    'Jerusalem|Asia/Jerusalem|Israel|Tel Aviv IST',
    'Amman|Asia/Amman|Jordan|',
    'Beirut|Asia/Beirut|Lebanon|',
    'Baku|Asia/Baku|Azerbaijan|',
    'Tbilisi|Asia/Tbilisi|Georgia|',
    'Yerevan|Asia/Yerevan|Armenia|',

    // South & Central Asia
    'Mumbai|Asia/Kolkata|India|IST Bombay Maharashtra',
    'New Delhi|Asia/Kolkata|India|Delhi IST',
    'Bengaluru|Asia/Kolkata|India|Bangalore IST Karnataka',
    'Hyderabad|Asia/Kolkata|India|IST Telangana',
    'Chennai|Asia/Kolkata|India|Madras IST',
    'Kolkata|Asia/Kolkata|India|Calcutta IST',
    'Pune|Asia/Kolkata|India|IST',
    'Ahmedabad|Asia/Kolkata|India|IST Gujarat',
    'Karachi|Asia/Karachi|Pakistan|PKT',
    'Lahore|Asia/Karachi|Pakistan|',
    'Islamabad|Asia/Karachi|Pakistan|',
    'Dhaka|Asia/Dhaka|Bangladesh|',
    'Kathmandu|Asia/Kathmandu|Nepal|',
    'Colombo|Asia/Colombo|Sri Lanka|',
    'Thimphu|Asia/Thimphu|Bhutan|',
    'Malé|Indian/Maldives|Maldives|',
    'Kabul|Asia/Kabul|Afghanistan|',
    'Tashkent|Asia/Tashkent|Uzbekistan|',
    'Almaty|Asia/Almaty|Kazakhstan|',

    // East & Southeast Asia
    'Beijing|Asia/Shanghai|China|CST',
    'Shanghai|Asia/Shanghai|China|CST',
    'Shenzhen|Asia/Shanghai|China|',
    'Guangzhou|Asia/Shanghai|China|',
    'Hong Kong|Asia/Hong_Kong|Hong Kong|HKT',
    'Macau|Asia/Macau|Macau|',
    'Taipei|Asia/Taipei|Taiwan|',
    'Tokyo|Asia/Tokyo|Japan|JST',
    'Osaka|Asia/Tokyo|Japan|',
    'Seoul|Asia/Seoul|South Korea|KST',
    'Ulaanbaatar|Asia/Ulaanbaatar|Mongolia|',
    'Singapore|Asia/Singapore|Singapore|SGT',
    'Kuala Lumpur|Asia/Kuala_Lumpur|Malaysia|MYT',
    'Bangkok|Asia/Bangkok|Thailand|ICT',
    'Ho Chi Minh City|Asia/Ho_Chi_Minh|Vietnam|Saigon',
    'Hanoi|Asia/Ho_Chi_Minh|Vietnam|',
    'Phnom Penh|Asia/Phnom_Penh|Cambodia|',
    'Vientiane|Asia/Vientiane|Laos|',
    'Yangon|Asia/Rangoon|Myanmar|Rangoon Burma',
    'Jakarta|Asia/Jakarta|Indonesia|WIB',
    'Bali|Asia/Makassar|Indonesia|WITA Denpasar',
    'Manila|Asia/Manila|Philippines|PHT',

    // Oceania
    'Sydney|Australia/Sydney|Australia|AEST AEDT Canberra',
    'Melbourne|Australia/Melbourne|Australia|AEST AEDT',
    'Brisbane|Australia/Brisbane|Australia|AEST Queensland',
    'Perth|Australia/Perth|Australia|AWST',
    'Adelaide|Australia/Adelaide|Australia|ACST ACDT',
    'Darwin|Australia/Darwin|Australia|ACST',
    'Auckland|Pacific/Auckland|New Zealand|NZST NZDT',
    'Wellington|Pacific/Auckland|New Zealand|',
    'Suva|Pacific/Fiji|Fiji|',
    'Port Moresby|Pacific/Port_Moresby|Papua New Guinea|',
    'Nouméa|Pacific/Noumea|New Caledonia|',
    'Guam|Pacific/Guam|Guam|',
    'Papeete|Pacific/Tahiti|French Polynesia|Tahiti',
    'Apia|Pacific/Apia|Samoa|',
    "Nuku'alofa|Pacific/Tongatapu|Tonga|",

    // Universal
    'UTC|UTC|Coordinated Universal Time|GMT Zulu'
  ]
};
